fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.16.0"
    transition:
      repo: "puppetlabs/transition"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "2.1.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "4.4.0"
  symlinks:
    puppet_agent: "#{source_dir}"
