fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "2.4.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "7.4.2"
    translate:
      repo: "puppetlabs/translate"
      ref: "1.2.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
    facts:
      repo: "puppetlabs/facts"
      ref: "0.5.1"
  symlinks:
    puppet_agent: "#{source_dir}"
