---
language: ruby
dist: trusty
sudo: false
bundler_args: --without system_tests --full-index
before_script: cat Gemfile.lock
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake validate lint
  - bundle exec rake parallel_spec
matrix:
  include:
# Disabling 1.8.7 as it no longer plays nice
#     - rvm: 1.8.7
#       env: PUPPET_GEM_VERSION="~> 3.7.5"
#     - rvm: 1.8.7
#       env: PUPPET_GEM_VERSION="~> 3.8.1"
# Disabling as puppet-module-gems only supports ruby >= 2.1.X
#    - rvm: 1.9.3
#      env: PUPPET_GEM_VERSION="~> 3.8.1"  FUTURE_PARSER="yes"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.8"  FUTURE_PARSER="yes"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 2.3.4
      env: PUPPET_GEM_VERSION="~> 4.10"
    - rvm: 2.3.4
      env: PUPPET_GEM_VERSION="~> 5.0.1"
